### ISSUE TITLE
converjon-cli not working

### ISSUE THREAD

**Issue by lnwdr** [berlinonline/converjon#126]
conversion-cli is currently not working at all. recent changes in the locking module need to be brought over to this, too.

**Comment by neffets** [comment]
Just trapped in.

Have a bug in converjon and wanted checked it on commandline. Argh - its not working, found another (this) bug.
Is the resolving on work? When it will come?

**Comment by neffets** [comment]
<pre>
converjon-cli thumbnail_wanderroutenflyer.pdf.png test.png
/usr/lib/node_modules/converjon/bin/converjon-cli.js:98
    source: lock(infile),
            ^
TypeError: object is not a function
    at Object.<anonymous> (/usr/lib/node_modules/converjon/bin/converjon-cli.js:98:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
</pre>

**Comment by neffets** [comment]
Bug still active. will it be fixed?
